<?php

namespace WebinoDraw\Stdlib;

/**
 * Test class for VarTranslator.
 * Generated by PHPUnit on 2013-03-18 at 20:26:26.
 */
class VarTranslatorTest
        extends \PHPUnit_Framework_TestCase
{

    /**
     * @var VarTranslator
     */
    protected $object;

    /**
     * @var \Zend\ServiceManager\AbstractPluginManager
     */
    protected $pluginHelper;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->pluginHelper = $this->getMock('Zend\ServiceManager\AbstractPluginManager');
        $this->object = new VarTranslator($this->pluginHelper);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::makeVar
     * @todo Implement testMakeVar().
     */
    public function testMakeVar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::containsVar
     * @todo Implement testContainsVar().
     */
    public function testContainsVar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::makeVarKeys
     * @todo Implement testMakeVarKeys().
     */
    public function testMakeVarKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::translateString
     */
    public function testTranslateString()
    {
        $string = 'before {$var} after';
        $expected = 'before value after';
        $translation = new \ArrayObject(array('{$var}' => 'value'));
        $result = $this->object->translateString($string, $translation);

        $this->assertEquals($expected, $result);
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::translate
     * @todo Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::translationMerge
     * @todo Implement testTranslationMerge().
     */
    public function testTranslationMerge()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::translationDefaults
     * @todo Implement testTranslationDefaults().
     */
    public function testTranslationDefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::translationFetch
     * @todo Implement testTranslationFetch().
     */
    public function testTranslationFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::applyHelper
     * @todo Implement testApplyHelper().
     */
    public function testApplyHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Stdlib\VarTranslator::applyFilter
     * @todo Implement testApplyFilter().
     */
    public function testApplyFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
