language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  
before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - php composer.phar self-update
  - php composer.phar install
  - rm -rf vendor/webino/webino-draw
  - cp -r ../WebinoDraw vendor/webino/webino-draw

script:
  - cd vendor/webino/webino-draw
  - phpunit
