language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - cd test
  - phpunit --coverage-clover ../build/logs/clover.xml
  - cd ..
  - vendor/bin/phpcs --standard=PSR2 src test

after_script:
  - vendor/bin/coveralls -v
