language: php
php:
  - 7.1
before_install:
  - curl -s https://get.webino.org/support/travis/before-install | sudo -E sh
install:
  - curl -s https://get.webino.org/support/travis/install | sh
before_script:
  - curl -s https://get.webino.org/support/travis/before-script | sh
script:
  - curl -s https://get.webino.org/support/travis/script | sh
after_failure:
  - curl -s https://get.webino.org/support/travis/after-failure | sh
after_success:
  - curl -s https://get.webino.org/support/travis/after-success | sh
env:
  global:
    - URI=http://localhost:8000/
    - BROWSER=firefox
    - GH_REF=github.com/webino/WebinoDraw
    - secure: COrEIOrhD8yam8Gze+6W84OPRkqrHp9ol/Fn+mXZCcuRqcplTt2/vcA1N23Z/GMO6oMxS+KmD82fjOEGW86/1wFJVxAdz8AROe1KmGAbzO5dDNDxTNclmq6jDHDQzqwpr4DlFK9+8ktrIXp/dgFa6NJ5P3LvVJOlGi8UIyBOJkI=
