language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install

script:
  - cd test
  - phpunit --coverage-clover build/logs/clover.xml
  - cd ..
  - vendor/bin/phpcs --standard=PSR2 src

after_script:
  - vendor/bin/coveralls -v
