language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  
before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - php composer.phar self-update
  - php composer.phar install

script:
  - cd tests
  - phpunit
