<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebinoDraw\Exception\ExceptionInterface'          => __DIR__ . '/src/WebinoDraw/Exception/ExceptionInterface.php',
    'WebinoDraw\Exception\InvalidArgumentException'    => __DIR__ . '/src/WebinoDraw/Exception/InvalidArgumentException.php',
    'WebinoDraw\Exception\MissingPropertyException'    => __DIR__ . '/src/WebinoDraw/Exception/MissingPropertyException.php',
    'WebinoDraw\Exception\RuntimeException'            => __DIR__ . '/src/WebinoDraw/Exception/RuntimeException.php',
    'WebinoDraw\Exception\InvalidInstructionException' => __DIR__ . '/src/WebinoDraw/Exception/InvalidInstructionException.php',
    'WebinoDraw\Mvc\Service\ViewDrawStrategyFactory'   => __DIR__ . '/src/WebinoDraw/Mvc/Service/ViewDrawStrategyFactory.php',
    'WebinoDraw\Stdlib\DrawInstructions'               => __DIR__ . '/src/WebinoDraw/Stdlib/DrawInstructions.php',
    'WebinoDraw\Stdlib\VarTranslator'                  => __DIR__ . '/src/WebinoDraw/Stdlib/VarTranslator.php',
    'WebinoDraw\View\Helper\AbstractDrawElement'       => __DIR__ . '/src/WebinoDraw/View/Helper/AbstractDrawElement.php',
    'WebinoDraw\View\Helper\DrawHelperInterface'       => __DIR__ . '/src/WebinoDraw/View/Helper/DrawHelperInterface.php',
    'WebinoDraw\View\Helper\DrawElement'               => __DIR__ . '/src/WebinoDraw/View/Helper/DrawElement.php',
    'WebinoDraw\View\Helper\AbstractDrawHelper'        => __DIR__ . '/src/WebinoDraw/View/Helper/AbstractDrawHelper.php',
    'WebinoDraw\View\Strategy\DrawStrategy'            => __DIR__ . '/src/WebinoDraw/View/Strategy/DrawStrategy.php',
    'WebinoDraw\Dom\XpathUtils'                        => __DIR__ . '/src/WebinoDraw/Dom/XpathUtils.php',
    'WebinoDraw\Dom\NodeList'                          => __DIR__ . '/src/WebinoDraw/Dom/NodeList.php',
    'WebinoDraw\Dom\Draw'                              => __DIR__ . '/src/WebinoDraw/Dom/Draw.php',
);