<?php
/** @var \WebinoDraw\Debugger\DrawPanel $this */
/** @var \WebinoDraw\Service\DrawProfiler $profiler */
$profiler = $this->getProfiler();
?>
<style>
    .webino-draw-highlight {
        position: absolute;
        z-index: 9999;
        background: #159;
        opacity: .5;
    }

    .webino-draw-highlight-link strong:hover {
        text-decoration: underline !important;
    }

    .webino-draw-highlight-link .missing,
    .webino-draw-highlight-link .missing:hover {
        text-decoration: line-through !important;
        cursor: not-allowed !important;
    }
</style>
<h1><?= $this->escapeHtml($this->title) ?></h1>
<div class="tracy-inner tracy-inner-box" style="padding: 10px">
    <div class="tracy-inner-container">
        <p>Total time: <?= $this->escapeHtml(sprintf('%s ms', number_format($profiler->getTotalTime() * 1000, 1, '.', ' '))) ?></p>
        <br />
        <div>
            <?php
            $n = 0;
            foreach ($profiler->getData() as $key => $data):
                $n++;
                ?>
                <span class="webino-draw-highlight-link">
                    <?php
                    $locator = join('\', \'', empty($data['spec']['locator']) ? [] : (array) $data['spec']['locator']);
                    $locator = '[\'' . strtr($locator, [PHP_EOL => '', '"' => '\\\'']) . '\']';
                    ?>
                    <strong style="font-size: larger; cursor: pointer;" class="<?php if (empty($data['time'])) echo 'missing' ?>"
                            onmouseover="webinoDrawHighlight(<?= $this->escapeHtml($locator) ?>)"
                            onmouseout="webinoDrawRemoveHighlight()">
                        <?= $this->escapeHtml($n . '. ' . $key) ?>
                    </strong>
                    <?= $this->escapeHtml($data['time'] ? sprintf(' / %s ms', number_format($data['time'] * 1000, 1, '.', ' ')) : '') ?>
                </span>
                <?= $this->dump($data['spec']) ?>
                <br />
            <?php endforeach; ?>
        </div>
    </div>
</div>
<script>
    function getElementsByXpath(path) {
        console.log(path);
        return document.evaluate(path, document, null, XPathResult.ANY_TYPE, null);
    }

    function webinoDrawHighlight(locator)
    {
        var l = locator.length;
        for (var i = 0; i < l; i++) {
            if ('xpath=' === locator[i].substring(0, 6)) {
                console.log(getElementsByXpath(locator[i].substring(6)));
                return;
            }

            var q = locator[i].split('[');
            if (q.length > 1) {
                // nth-child
                q[0]+= ':nth-child(' + parseInt(q[1]) + ')';
            }

            var elms = document.querySelectorAll(q[0]);
            webinoDrawHiglightElements(elms);
        }
    }

    function webinoDrawHiglightElements(elms)
    {
        var l = elms.length;
        if (l > 100) {
            console.log('WebinoDraw: too much elements');
            return;
        }

        var doc = document.documentElement;
        var left = (window.pageXOffset || doc.scrollLeft) - (doc.clientLeft || 0);
        var top = (window.pageYOffset || doc.scrollTop)  - (doc.clientTop || 0);

        for (var i = 0; i < l; i++) {
            var mask = document.createElement('div');
            mask.className = 'webino-draw-highlight';

            var rect = elms[i].getBoundingClientRect();

            mask.style.width = elms[i].offsetWidth + 'px';
            mask.style.height = elms[i].offsetHeight + 'px';
            mask.style.top = top + rect.top + 'px';
            mask.style.left = left + rect.left + 'px';

            document.body.appendChild(mask);
        }
    }

    function webinoDrawRemoveHighlight()
    {
        var elms = document.getElementsByClassName('webino-draw-highlight');
        var l = elms.length;
        var toRemove = [];
        for (var i = 0; i < l; i++) {
            toRemove.push(elms[i]);
        }
        for (var n = 0; n < l; n++) {
            console.log(toRemove[n]);
            toRemove[n].parentNode.removeChild(toRemove[n]);
        }
    }
</script>
