<?php

namespace WebinoDraw\Dom;

/**
 * Test class for Element.
 * Generated by PHPUnit on 2013-05-10 at 09:45:42.
 */
class ElementTest
    extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Element
     */
    protected $object;

    /**
     *
     * @var \DOMDocument
     */
    protected $doc;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Element('test_element');

        $this->doc  = new \DOMDocument;
        $this->doc->appendChild($this->object);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoDraw\Dom\Element::getInnerHtml
     */
    public function testGetInnerHtml()
    {
        $html = '<test_child01/><test_child02>test val 02</test_child02>';
        $frag = $this->doc->createDocumentFragment();
        $frag->appendXML($html);

        $this->object->appendChild($frag);

        $this->assertSame($html, $this->object->getInnerHtml());
    }

    /**
     * @covers WebinoDraw\Dom\Element::getProperties
     */
    public function testGetProperties()
    {
        $input = array(
            'nodeValue' => 'test node value',
            'attr01' => 'attr01Val',
            'attr02' => 'attr02Val',
        );

        $this->object->nodeValue = $input['nodeValue'];

        next($input);
        $this->object->setAttribute(key($input), current($input));

        next($input);
        $this->object->setAttribute(key($input), current($input));

        $this->assertSame($input, $this->object->getProperties());
    }

    /**
     * @covers WebinoDraw\Dom\Element::getProperties
     */
    public function testGetPropertiesWithPrefix()
    {
        $prefix = '___';
        $input = array(
            'nodeValue' => 'test node value',
            'attr01' => 'attr01Val',
            'attr02' => 'attr02Val',
        );
        $expected = array(
            $prefix . 'nodeValue' => 'test node value',
            $prefix . 'attr01' => 'attr01Val',
            $prefix . 'attr02' => 'attr02Val',
        );

        $this->object->nodeValue = $input['nodeValue'];

        next($input);
        $this->object->setAttribute(key($input), current($input));

        next($input);
        $this->object->setAttribute(key($input), current($input));

        $this->assertSame($expected, $this->object->getProperties($prefix));
    }
}
