<?php
/**
 * Webino (http://webino.sk)
 *
 * @link        https://github.com/webino/WebinoDraw for the canonical source repository
 * @copyright   Copyright (c) 2012-2014 Webino, s. r. o. (http://webino.sk)
 * @author      Peter Bačinský <peter@bacinsky.sk>
 * @license     BSD-3-Clause
 */

namespace WebinoDraw\Event;

use PHPUnit_Framework_Assert as PhpUnitAssert;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-31 at 21:50:25.
 */
class DrawFormEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DrawFormEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DrawFormEvent;
    }

    /**
     * @covers WebinoDraw\Event\DrawFormEvent::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Event\DrawFormEvent::setForm
     */
    public function testSetForm()
    {
        $form = $this->getMock('Zend\Form\Form');

        // test fluent
        $this->assertSame($this->object, $this->object->setForm($form));
        $this->assertEquals($form, $this->object->getParam('form'));
        $this->assertEquals($form, PhpUnitAssert::readAttribute($this->object, 'form'));
    }
}
