<?php

namespace WebinoDraw\Options;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-13 at 18:51:59.
 */
class ModuleOptionsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ModuleOptions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModuleOptions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::getInstructions
     */
    public function testGetInstructions()
    {
        $this->assertInstanceOf('WebinoDraw\Instructions\InstructionsInterface', $this->object->getInstructions());
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::setInstructions
     * @todo   Implement testSetInstructions().
     */
    public function testSetInstructions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::getInstructionSet
     * @todo   Implement testGetInstructionSet().
     */
    public function testGetInstructionSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::setInstructionSet
     * @todo   Implement testSetInstructionSet().
     */
    public function testSetInstructionSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::instructionsFromSet
     * @todo   Implement testInstructionsFromSet().
     */
    public function testInstructionsFromSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::getAjaxContainerXpath
     * @todo   Implement testGetAjaxContainerXpath().
     */
    public function testGetAjaxContainerXpath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::setAjaxContainerXpath
     * @todo   Implement testSetAjaxContainerXpath().
     */
    public function testSetAjaxContainerXpath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::getAjaxFragmentXpath
     * @todo   Implement testGetAjaxFragmentXpath().
     */
    public function testGetAjaxFragmentXpath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\Options\ModuleOptions::setAjaxFragmentXpath
     * @todo   Implement testSetAjaxFragmentXpath().
     */
    public function testSetAjaxFragmentXpath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
