<?php
/**
 * Webino (http://webino.sk)
 *
 * @link        https://github.com/webino/WebinoDraw for the canonical source repository
 * @copyright   Copyright (c) 2012-2017 Webino, s. r. o. (http://webino.sk)
 * @author      Peter Bačinský <peter@bacinsky.sk>
 * @license     BSD-3-Clause
 */

namespace WebinoDraw\Form\View\Helper;

use Zend\View\Renderer\PhpRenderer;
use Zend\Form\Element;
use Zend\Form\View\Helper\FormInput;
use OutOfRangeException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-31 at 22:06:06.
 */
class FormElementTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FormElement
     */
    protected $object;

    /**
     * @var PhpRenderer
     */
    protected $view;

    /**
     * @var Element
     */
    protected $element;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object  = new FormElement;
        $this->view    = $this->getMock(PhpRenderer::class);
        $this->object->setView($this->view);
        $this->element = $this->getMock(Element::class);
    }

    /**
     * @covers WebinoDraw\Form\View\Helper\FormElement::renderHelper
     */
    public function testRenderHelperByOption()
    {
        $viewHelper = $this->getMock(FormInput::class);
        $helperName = 'test_view_helper';
        $expected   = md5(__METHOD__);

        $viewHelper->expects($this->once())
            ->method('__invoke')
            ->will($this->returnValue($expected));

        $this->element->expects($this->once())
            ->method('getOption')
            ->with('view_helper')
            ->will($this->returnValue($helperName));

        $this->view->expects($this->once())
            ->method('plugin')
            ->with($this->equalTo($helperName))
            ->will($this->returnValue($viewHelper));

        $result = $this->object->render($this->element);

        $this->assertSame($result, $expected);
    }

    /**
     * @covers WebinoDraw\Form\View\Helper\FormElement::renderHelper
     */
    public function xtestResolveHelperByEmptyOption()
    {
        $this->setExpectedException(OutOfRangeException::class);

        $helperName = '';

        $this->element->expects($this->once())
            ->method('getOption')
            ->with('view_helper')
            ->will($this->returnValue($helperName));

        $this->view->expects($this->never())
            ->method('plugin');

        $this->object->render($this->element);
    }
}
