<?php
/**
 * Webino (http://webino.sk)
 *
 * @link        https://github.com/webino/WebinoDraw for the canonical source repository
 * @copyright   Copyright (c) 2013 Webino, s. r. o. (http://webino.sk)
 * @author      Peter Bačinský <peter@bacinsky.sk>
 * @license     New BSD License
 */

namespace WebinoDraw\View\Helper;

use DOMDocument;

/**
 * Test class for AbstractDrawHelper.
 * Generated by PHPUnit on 2013-04-02 at 20:29:31.
 */
class AbstractDrawHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractDrawHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestDrawHelperDummy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getCache
     * @todo Implement testGetCache().
     */
    public function testGetCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setCache
     * @todo Implement testSetCache().
     */
    public function testSetCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getEvent
     * @todo Implement testGetEvent().
     */
    public function testGetEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setEvent
     * @todo Implement testSetEvent().
     */
    public function testSetEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getEventManager
     * @todo Implement testGetEventManager().
     */
    public function testGetEventManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setEventManager
     * @todo Implement testSetEventManager().
     */
    public function testSetEventManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getFilterPluginManager
     * @todo Implement testGetFilterPluginManager().
     */
    public function testGetFilterPluginManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setFilterPluginManager
     * @todo Implement testSetFilterPluginManager().
     */
    public function testSetFilterPluginManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getVars
     * @todo Implement testGetVars().
     */
    public function testGetVars()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setVars
     * @todo Implement testSetVars().
     */
    public function testSetVars()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setVarTranslator
     * @todo Implement testSetVarTranslator().
     */
    public function testSetVarTranslator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getVarTranslator
     * @todo Implement testGetVarTranslator().
     */
    public function testGetVarTranslator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getTranslationPrototype
     * @todo Implement testGetTranslationPrototype().
     */
    public function testGetTranslationPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setTranslationPrototype
     * @todo Implement testSetTranslationPrototype().
     */
    public function testSetTranslationPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::cloneTranslationPrototype
     * @todo Implement testCloneTranslationPrototype().
     */
    public function testCloneTranslationPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::getInstructionsPrototype
     * @todo Implement testGetInstructionsPrototype().
     */
    public function testGetInstructionsPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::setInstructionsPrototype
     * @todo Implement testSetInstructionsPrototype().
     */
    public function testSetInstructionsPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::cloneInstructionsPrototype
     * @todo Implement testCloneInstructionsPrototype().
     */
    public function testCloneInstructionsPrototype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::applyVarTranslator
     * @todo Implement testApplyVarTranslator().
     */
    public function testApplyVarTranslator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\AbstractDrawHelper::nodeTranslation
     */
    public function testNodeTranslation()
    {
        $value   = 'test node value';
        $attribs = array(
            'attr1' => 'testAttr1',
            'attr2' => 'testAttr2',
        );
        $prefix  = '_';

        $dom  = new DOMDocument;
        $dom->registerNodeClass('DOMElement', 'WebinoDraw\Dom\Element');
        $dom->loadXML('<dummy/>');
        $node = $dom->documentElement;

        $node->nodeValue = $value;

        $node->setAttribute(key($attribs), current($attribs));
        next($attribs);
        $node->setAttribute(key($attribs), current($attribs));

        $translation = $this->object->nodeTranslation($node);

        $this->assertEquals($value, $translation[$prefix . 'nodeValue']);

        reset($attribs);

        $key = key($attribs);
        $this->assertEquals($attribs[$key], $translation[$prefix . $key]);

        $key = key($attribs);
        $this->assertEquals($attribs[$key], $translation[$prefix . $key]);
    }
}
