<?php
/**
 * Webino (http://webino.sk)
 *
 * @link        https://github.com/webino/WebinoDraw for the canonical source repository
 * @copyright   Copyright (c) 2012-2014 Webino, s. r. o. (http://webino.sk)
 * @author      Peter Bačinský <peter@bacinsky.sk>
 * @license     New BSD License
 */

namespace WebinoDraw\View\Helper;

/**
 * Test class for DrawPagination.
 * Generated by PHPUnit on 2013-05-31 at 23:01:46.
 */
class DrawPaginationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DrawPagination
     */
    protected $object;

    /**
     * @var WebinoDraw\Dom\NodeList
     */
    protected $nodeList;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object   = new DrawPagination;
        $this->nodeList = $this->getMock('WebinoDraw\Dom\NodeList', array(), array(), '', null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WebinoDraw\View\Helper\DrawPagination::setServiceLocator
     * @todo Implement testSetServiceLocator().
     */
    public function testSetServiceLocator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\DrawPagination::getServiceLocator
     * @todo Implement testGetServiceLocator().
     */
    public function testGetServiceLocator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebinoDraw\View\Helper\DrawPagination::drawNodes
     * @todo Implement testDrawNodes().
     */
    public function testDrawNodes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $paginatorName = 'TestPaginator';
        $spec = array('paginator' => $paginatorName);

        $this->object->drawNodes($this->nodeList, $spec);
    }
}
